---
skylounge-config:
  id: "skylounge.yml"
  uri: "sky-lounge/hello-cf/skylounge.yml"
  oid: "75a79820d2670f40e4716de8f640bd48d9c329c1"
  version-url: "/sky-lounge/hello-cf/blob/75a79820d2670f40e4716de8f640bd48d9c329c1/skylounge.yml"
blueprint:
  id: "blueprint"
  uri: "sky-lounge/skylounge-library/blueprints/cloudfoundry/bosh/blueprint.yml"
  oid: "6444ee16c91676731fd8d7b4896616fdbf1df808"
  version-url: "/sky-lounge/skylounge-library/blob/6444ee16c91676731fd8d7b4896616fdbf1df808/blueprints/cloudfoundry/bosh/blueprint.yml"
workflows:
- id: "development"
  uri: "sky-lounge/skylounge-library/blueprints/cloudfoundry/bosh/workflow-templates/development.yml"
  oid: "03bb543ebe12a592f5eab8a9d3b9cb44b29c665d"
  version-url: "/sky-lounge/skylounge-library/blob/03bb543ebe12a592f5eab8a9d3b9cb44b29c665d/blueprints/cloudfoundry/bosh/workflow-templates/development.yml"
  jobs:
  - id: "integration-test"
    uri: "sky-lounge/hello-cf/skylounge/integration-test.yml"
    oid: "b5d89472a0777a0c5a2c515d2626f148c23ce086"
    version-url: "/sky-lounge/hello-cf/blob/b5d89472a0777a0c5a2c515d2626f148c23ce086/skylounge/integration-test.yml"
  steps:
  - id: "unit-test"
    uri: "sky-lounge/skylounge-library/steps/unit-test/nginx/unit-test.yml"
    oid: "4a9aebc54594e4ff87c4950447ebe4536c6d1437"
    version-url: "/sky-lounge/skylounge-library/blob/4a9aebc54594e4ff87c4950447ebe4536c6d1437/steps/unit-test/nginx/unit-test.yml"
  - id: "pre-deploy"
    uri: "sky-lounge/skylounge-library/steps/no-step/step.yml"
    oid: "7cdeefcdb2fda28c933ff6aba07369960e7437c8"
    version-url: "/sky-lounge/skylounge-library/blob/7cdeefcdb2fda28c933ff6aba07369960e7437c8/steps/no-step/step.yml"
  - id: "deploy"
    uri: "sky-lounge/skylounge-library/steps/cloudfoundry/deploy/deploy.yml"
    oid: "457ed2013e373c0ab7bffdf4f48dc20ca61e965a"
    version-url: "/sky-lounge/skylounge-library/blob/457ed2013e373c0ab7bffdf4f48dc20ca61e965a/steps/cloudfoundry/deploy/deploy.yml"
- id: "promote"
  uri: "sky-lounge/skylounge-library/blueprints/cloudfoundry/bosh/workflow-templates/promote.yml"
  oid: "34b1801ea1c19ebbcfa242a78f2d47477c8cad73"
  version-url: "/sky-lounge/skylounge-library/blob/34b1801ea1c19ebbcfa242a78f2d47477c8cad73/blueprints/cloudfoundry/bosh/workflow-templates/promote.yml"
  jobs: []
  steps: []
