---
skylounge-config:
  id: "skylounge.yml"
  uri: "sky-lounge/hello-cf/skylounge.yml"
  oid: "620f027d6454e82cd8598bf8ec37df930e094609"
  version-url: "/sky-lounge/hello-cf/blob/620f027d6454e82cd8598bf8ec37df930e094609/skylounge.yml"
blueprint:
  id: "blueprint"
  uri: "sky-lounge/skylounge-library/blueprints/cloudfoundry/bosh/blueprint.yml"
  oid: "6444ee16c91676731fd8d7b4896616fdbf1df808"
  version-url: "/sky-lounge/skylounge-library/blob/6444ee16c91676731fd8d7b4896616fdbf1df808/blueprints/cloudfoundry/bosh/blueprint.yml"
workflows:
- id: "development"
  uri: "sky-lounge/skylounge-library/blueprints/cloudfoundry/bosh/workflow-templates/development.yml"
  oid: "f777cdc88a26bc5992def8040d0c126f1282433e"
  version-url: "/sky-lounge/skylounge-library/blob/f777cdc88a26bc5992def8040d0c126f1282433e/blueprints/cloudfoundry/bosh/workflow-templates/development.yml"
  jobs:
  - id: "integration-test"
    uri: "sky-lounge/hello-cf/skylounge/integration-test.yml"
    oid: "988a825e2c963e95b727c772cee288fc55a3f7c3"
    version-url: "/sky-lounge/hello-cf/blob/988a825e2c963e95b727c772cee288fc55a3f7c3/skylounge/integration-test.yml"
  steps:
  - id: "unit-test"
    uri: "sky-lounge/skylounge-library/steps/unit-test/nginx/unit-test.yml"
    oid: "d679aca0ed87a9a1426343f620eefbf136450dea"
    version-url: "/sky-lounge/skylounge-library/blob/d679aca0ed87a9a1426343f620eefbf136450dea/steps/unit-test/nginx/unit-test.yml"
  - id: "pre-deploy"
    uri: "sky-lounge/skylounge-library/steps/no-step/step.yml"
    oid: "7cdeefcdb2fda28c933ff6aba07369960e7437c8"
    version-url: "/sky-lounge/skylounge-library/blob/7cdeefcdb2fda28c933ff6aba07369960e7437c8/steps/no-step/step.yml"
  - id: "deploy"
    uri: "sky-lounge/skylounge-library/steps/cloudfoundry/deploy/deploy.yml"
    oid: "3376cfba195f8818182705e5c3ca2e09527c4a1e"
    version-url: "/sky-lounge/skylounge-library/blob/3376cfba195f8818182705e5c3ca2e09527c4a1e/steps/cloudfoundry/deploy/deploy.yml"
- id: "promote"
  uri: "sky-lounge/skylounge-library/blueprints/cloudfoundry/bosh/workflow-templates/promote.yml"
  oid: "34b1801ea1c19ebbcfa242a78f2d47477c8cad73"
  version-url: "/sky-lounge/skylounge-library/blob/34b1801ea1c19ebbcfa242a78f2d47477c8cad73/blueprints/cloudfoundry/bosh/workflow-templates/promote.yml"
  jobs: []
  steps: []
