---
applications:
  - name: hello-cf
    buildpacks:
      - https://github.com/cloudfoundry/nginx-buildpack.git
    disk_quota: 64M
    instances: 1
    memory: 32M
    path: ../src/
    routes:
      - route: hello-cf.de.a9sapp.eu
