---
name: Pull Request
on:
  pull_request:
    types:
    - opened
    - reopened
    paths:
    - src/**
    - skylounge/**
    - cf/dev-manifest.yml
permissions:
  contents: read
  pull-requests: write
jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Unit test
      run: |
        if [ ! -f "src/nginx.conf" ]; then
            echo "Missing nginx.conf"
            exit 1
        fi
  dependency-review:
    name: GitHub Dependency Review
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Dependency Review
      uses: actions/dependency-review-action@main
      with:
        config-file: "${{ env.CONFIG_FILE }}"
        external-repo-token: "${{ secrets.LIBRARY_TOKEN }}"
      env:
        CONFIG_FILE: sky-lounge/skylounge-library/jobs/github/security/dependency-review/config/cloud-gov.yml@main
