---
name: Scan Pull Request
on:
- pull_request
permissions:
  contents: read
  pull-request: write
jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Unit test
      run: |
        if [ ! -f "src/nginx.conf" ]; then
            echo "Missing nginx.conf"
            exit 1
        fi
  dependency-review:
    name: GitHub Dependency Review
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        config-file: "${{ env.CONFIG_FILE }}"
        external-repo-token: "${{ env.EXTERNAL_REPO_TOKEN }}"
      env:
        CONFIG_FILE: sky-lounge/skylounge-library/jobs/github/security/dependency-review/config/cloud-gov.yml@main
        EXTERNAL_REPO_TOKEN: "${{ secrets.LIBRARY_TOKEN }}"
