---
name: Test
on:
  workflow_dispatch:
jobs:
  deployed-version:
    name: Update deployed version
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
      - name: Update version
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@skylounge.io"
          echo "${{ github.sha }}" > .github/development-version.txt
          git add .github/development-version.txt
          git commit -m "update development version: ${{ github.sha }}"
          git pull --rebase
          git push
          
    
