---
name: Test
on:
  workflow_dispatch:
jobs:
  deployed-version:
    name: Update deployed version
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Update Artifact Version
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables \
            -d '{"name":"DEV_VERSION","value":"1.0.0"}'
